### ISSUE TITLE
Crash when removing recent searches

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#85]
When I remove several recent searches separately the app crashes and closes. Looks like if I wait a couple seconds inbetween removing items it works though.

**Comment by sreilly** [comment]
I think I've fixed this for build 605, but am not completely sure because I couldn't reproduce the problem.

**Comment by thm** [comment]
Thanks, it only seems to happen when I remove items quickly after one another. Almost as if it can't handle the removal of more than one item at a time

**Comment by sreilly** [comment]
I believe this is fixed.  Can you try the latest build and let me know if it still occurs?

**Comment by thm** [comment]
It's still crashing for me (iPhone 6, iOS 8.4.1, app v607). It's difficult to isolate the issue, it doesn't happen all the time, but very often. Here's a quick video: http://cl.ly/1g0D3N3x3i40/crash.mp4

**Comment by thm** [comment]
I'm unable to reproduce this in the latest build (616), so I'm marking this complete

**Comment by ghost** [comment]
I'm still experiencing crashes when deleting recent searches. It occurs after several consecutive searches are deleted, but sometimes if I skip further down and delete a search term, it only takes a second or third deletion to crash it.
Diagnostic data is being shared automatically - not sure where it all ends up.
Version 6.0.2 (709), iOS 9.2, bug type: "109"

Let me know if you want a video. I can demonstrate both instances mentioned. I also have 7 or 8 crash reports in Diagnostic files that I could share with you privately, or I could provide the key identifiers.

**Comment by SwiftlyDeft** [comment]
@Calefornia does this happen if you go to Recent searches > tap on the + icon. The app crashes every time I tap the +, when I was going through some testing to see if it was the deletion process, it looks like it has to do with tapping the +. Give it a try and let me know. 

Thanks
Josiah Clumont

**Comment by ghost** [comment]
@SwiftlyDeft, you are correct. Wow, I never realized that was the actual problem. Swiping to delete works just fine as long as I don't touch the + icon.
Wondering why this same crash doesn't happen on the other recent searches list, accessed from the far left search icon. (The one used to essentially paste recent searches into the search bar).

**Comment by SwiftlyDeft** [comment]
@Calefornia no issues. I was playing around with it after i saw your issue come in on Slack. It was connected up to the debugger so made it a lot easier to figure out that it had to do with the + button. It's been updated. So after the next update of the app + will work on recent searches. 
It works on the search tab as there was a delegation issue with the recent/history view controller and how it handled the method, it was trying to do something it was not meant to. Thanks again for bringing this up.

**Comment by ghost** [comment]
@SwiftlyDeft, thanks! glad it's fixed

**Comment by ghost** [comment]
Experiencing the same bug again, when the + is tapped. Thought it was fixed, but I can't remember. Might not be high priority, so let me know if there's anything I can do to help. I have no clue where to begin...

**Comment by edgesince84** [comment]
Hi @Calefornia, I'm unable to reproduce this bug.  What version of iOS and the app are you experiencing this on?

**Comment by ghost** [comment]
Sorry, I should've included those. I'm on iOS 9.3.2, and the app is 6.0.2
(709). As far as I know, both are the latest updates.

**Comment by edgesince84** [comment]
@Calefornia I was just able to reproduce it now -- we'll put some eyes on it internally too, and if there's anything you can do to help, we'll definitely let you know!

**Comment by thm** [comment]
@Calefornia @edgesince84 the build that includes @SwiftlyDeft's fix for this issue hasn't been published to the App Store yet. We're close to pushing the update, then it should be fixed. I'm closing this, after the v6.0.3 update feel free to re-open if the bug still occurs.
